### ISSUE TITLE
Async callbacks

### ISSUE THREAD

**Issue by zloirock** [js-choi/proposal-array-from-async#4]
Now, in the spec draft we have:

<img width="722" alt="Снимок экрана 2021-09-01 в 14 04 01" src="https://user-images.githubusercontent.com/2213682/131627038-174c1472-2c51-4d50-804a-946a2ec6794a.png">

However, [in related methods of iterator helpers proposal](https://tc39.es/proposal-iterator-helpers/#sec-asynciteratorprototype.map), we await the result of the mapper:

<img width="430" alt="Снимок экрана 2021-09-01 в 14 05 19" src="https://user-images.githubusercontent.com/2213682/131627343-b03dfad3-7d82-4cb5-b121-490e259fd085.png">

It should be consistent.

**Comment by js-choi** [comment]
Thank you for catching this; this is a good point.

I agree that the mapper function should be considered as an async function and its results should be awaited, in order to match iterator-helpers’ behavior. I will change this later if there are no objections. CC: @codehag

**Comment by js-choi** [comment]
The [spec](https://jschoi.org/21/es-array-async-from/) and explainer have been updated in 15ed9ce2d47ba88c5dea8ba3a2a58cd4e36e4af7.
